//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobinor.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ccgEntities : DbContext
    {
        public ccgEntities()
            : base("name=ccgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MobileDetail> MobileDetails { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<DailerInfo> DailerInfoes { get; set; }
    }
}
