//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobinor.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailerInfo
    {
        public int Id { get; set; }
        public string DailerName { get; set; }
        public string DailerLink { get; set; }
        public string OperatorCode { get; set; }
        public Nullable<int> MobileId { get; set; }
        public Nullable<int> CountryId { get; set; }
    }
}
